name: Compile and pack to .pext
on:
  workflow_dispatch:
    inputs:
      release:
        description: Build for release
        type: boolean
        required: false
        default: false
  push:
    tags: 'v**'
jobs:
  compile-and-pack:
    runs-on: windows-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v6
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - run: >- 
          msbuild -t:Restore
          -p:Configuration=Release
          -p:Platform='Any CPU'
          -p:RestorePackagesConfig=true 
          ClearCookies.sln
      - run: >- 
          msbuild
          -p:Configuration=Release
          -p:Platform='Any CPU'
          ClearCookies.sln
      - name: Download Playnite
        uses: robinraju/release-downloader@v1
        with:
          repository: JosefNemec/Playnite
          latest: true
          fileName: '*.7z'
          tarBall: false
          zipBall: false
      - name: Decompress Playnite
        run: 7z x -bd -oplaynite *.7z
      - name: Packing extension with toolbox
        run: ./Toolbox.exe pack ../bin/Release ../output
        working-directory: playnite
      - uses: actions/upload-artifact@v6
        with:
          path: output/*.pext

  release:
    runs-on: ubuntu-latest
    needs: compile-and-pack
    if: ${{ github.event_name == 'push' || inputs.release && github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v7
    - name: Release on GitHub
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
          gh release create ${{ github.ref_name }}
          --repo ${{ github.repository }}
          --title ${{ github.ref_name }}
          --generate-notes
          *.pext
